// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppgmfqqwdqqflglzecxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwZ21mcXF3ZHFxZmxnbHplY3h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwOTI2NDEsImV4cCI6MjA3MjY2ODY0MX0.HHPi5Qd3uiGSZH9-dpGrKD3ligPLCzU_nYV7s8lf_Rc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});